version: '3.9'

services:
  back-end:
    build:
      context: .
      dockerfile: ./packages/back-end/Dockerfile
    image: back-end/latest
    expose:
      - '3000'

  front-end:
    depends_on:
      - back-end
    build:
      context: .
      dockerfile: ./packages/front-end/Dockerfile
    image: front-end/latest
    ports:
      - '80:80'
